#!/usr/bin/env python3

import asyncio
import sys
from googletrans import Translator

async def translate_text():
    async with Translator() as translator:
        result = await translator.translate(sys.argv[1])
        print(result.text)

asyncio.run(translate_text())

